#title: ğŸ’»â›³ğŸ‡
title: Jason Van Heerden
#description: fin
description:
 - "Final-year."
 - "BSc."
#Final-year BSc IT student with a proven academic record.
#Passionate about learning new things.
#Open-minded and curious, with an abundance mindset.
#Growth oriented.

logo: jason.png
theme: jekyll-theme-minimal
