#title: ğŸ’»â›³ğŸ‡
title: Jason Van Heerden
description: _Final-year BSc IT student with a proven academic record._ <br>
_Passionate about learning new things._ <br>
_Open-minded and curious, with an abundance mindset._ <br>
_Growth oriented._ <br>

logo: jason.png
theme: jekyll-theme-minimal
